services:
  postgres:
    image: postgres:16
    container_name: notifications_db
    environment:
      POSTGRES_DB: notifications-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: notifications_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

volumes:
  pgdata: